### ISSUE TITLE
关于retinaface模型的问题

### ISSUE THREAD

**Issue by CabbageWust** [xindongzhang/MNN_MSSD#12]
您好， 请问retinaface的mnn模型是由什么模型转换而来的。MNN好像没有提供 MXNet --> MNN的转换方法； 另外我用https://github.com/Charrin/RetinaFace-Cpp 提供的caffe模型进行转换， 碰到了错误：/MNN/tools/converter/source/caffe/Crop.cpp:40: Check failed: offsetSize >= 1 ==> crop offset error 。麻烦告知一下，thx 。

**Comment by CabbageWust** [comment]
作者您好， 我将caffe模型中的crop操作删除之后避免了之前的错误； 但是在用您的 caffe_retinaface.cpp测试自己转换的.mnn模型的时候， assert(cls.channel() == anchor_num*2); 这里会报错， 我的cls.channel()的值为20 ，您清楚这是什么问题吗

**Comment by xindongzhang** [comment]
@CabbageWust 这个问题我不清楚，你固定的输入大小是多少呢？

**Comment by CabbageWust** [comment]
我主要做了两次实验：
1. 直接下载insightface里的mnet训练好的模型（这里输入640 * 640），进行 MXNet --> CAFFE --> MNN 转换，利用您的cpp进行测试，错误如之前所述；
2.将输入改成 128 * 128，采用insightface里的代码训练，再进行模型转换并测试，报错和 1 一样。 
用您的 .mnn模型测试就挺好， 所以想知道您是怎么进行模型转换的。

**Comment by xindongzhang** [comment]
@CabbageWust 我把caffe proto上传到retinaface的工程目录下了，你可以参考一下

**Comment by CabbageWust** [comment]
@xindongzhang  thx, 参考您的 .prototxtx后解决了这个问题

**Comment by xindongzhang** [comment]
@CabbageWust 不客气

**Comment by bingkunlearn** [comment]
@CabbageWust 您好，请问　assert(cls.channel() == anchor_num*2)　这个问题是怎么解决的?需要修改.prototxt哪部分内容？

**Comment by CabbageWust** [comment]
@bingkunlearn 将.prototxt文件里的几处reshape操作的参数 改成和 @xindongzhang 提供的.prototxt文件一样，再转mnn就没问题了。

**Comment by bingkunlearn** [comment]
@CabbageWust  参考您的建议，已成功转换，谢谢！

**Comment by bingkunlearn** [comment]
@xindongzhang 作者您好，我在rk3399上ubuntu系统使用opencl调用mali-t860 gpu运行该算法，和cpu相比，runssession部分提速5倍以上，但把图片输入inputtensor和后处理的时间从不足1ms增加到40ms，请问使用opencl backend运行时，前后处理部分是不是需要改动？怎么修改? 谢谢

**Comment by bingkunlearn** [comment]
@xindongzhang 我仔细排查了，发现cpu运行时copyFromHostTensor和copyToHostTensor耗时忽略不计，但opencl运行时，copyFromHostTensor和copyToHostTensor耗时都需要31ms。请问数据传输有什么改进的方法吗？　谢谢

**Comment by zjd1988** [comment]
@bingkunlearn 这是因为MNN的opencl后端是非阻塞执行，runsession会立刻返回，直到你去取output_tensor时，会进行阻塞等待session推理完成，才能获取到结果。cpu后端则是runsession执行完成之后就能获取网络输出。
