### ISSUE TITLE
嵌入式主板

### ISSUE THREAD

**Issue by 850977164** [xindongzhang/MNN_MSSD#18]
你好，板子最大容量512M，项目整体大小明显超过板子容量，应该怎么解决这个问题？
谢谢

**Comment by xindongzhang** [comment]
> 你好，板子最大容量512M，项目整体大小明显超过板子容量，应该怎么解决这个问题？
> 谢谢

你可以上位机完成项目编译，然后再推到板子上面进行测试；如果不喜欢走交叉编译，可以挂载tf卡
