### ISSUE TITLE
Can I get mnn model for retinaface-mnetv2?

### ISSUE THREAD

**Issue by jeonginseo** [xindongzhang/MNN_MSSD#21]
I tested your retinaface models and it worked perfectly.
But the model you converted seems to be the retinaface based on mobilenet v1.
Can I get the model based on mobilenet v2?
Or, could you tell me how to convert these models from caffemodel to mnn?
I tried to convert the models including your folder, it failed all the time.

**Comment by xindongzhang** [comment]
> I tested your retinaface models and it worked perfectly.
> But the model you converted seems to be the retinaface based on mobilenet v1.
> Can I get the model based on mobilenet v2?
> Or, could you tell me how to convert these models from caffemodel to mnn?
> I tried to convert the models including your folder, it failed all the time.

If you want to convert retinaface-face series in to MNN, you need to remove some operations in the caffe graph definition. By the way, it is better to raise an issue in MNN. I think Community there will help you solve this problem.
