### ISSUE TITLE
安卓部署问题

### ISSUE THREAD

**Issue by yuzhijun2** [xindongzhang/MNN_MSSD#22]
您好，在安卓中，使用mnn的流程是先加载一遍mnn模型，再使用加载好的Mnn模型进行推断。
本人想把加载mnn模型和Mnn模型的推断都用C++实现，然后用java调用。请问如何实现呢。

**Comment by xindongzhang** [comment]
> 您好，在安卓中，使用mnn的流程是先加载一遍mnn模型，再使用加载好的Mnn模型进行推断。
> 本人想把加载mnn模型和Mnn模型的推断都用C++实现，然后用java调用。请问如何实现呢。

包一个jni接口就可以，网上可以找找教程。
