### ISSUE TITLE
NCHW and NHWC

### ISSUE THREAD

**Issue by alicera** [xindongzhang/MNN_MSSD#23]
SSD 寫到
> inputTensor->copyFromHostTensor(nhwc_Tensor);

疑问
nhwc_Tensor  到底是 NCHW 還是 NHWC
如果是 NHWC 格式 ，你不是说MNN模型要求输入为NCHW

**Comment by xindongzhang** [comment]
> SSD 寫到
> 
> > inputTensor->copyFromHostTensor(nhwc_Tensor);
> 
> 疑问
> nhwc_Tensor 到底是 NCHW 還是 NHWC
> 如果是 NHWC 格式 ，你不是说MNN模型要求输入为NCHW

这个只是对齐opencv端的输入，opencv端输出是nhwc的；mnn在做推理的时候会自动转化。

**Comment by alicera** [comment]
如何知道现在的格式     NHWC 格式 or NCHW
