### ISSUE TITLE
關於mssd的問題

### ISSUE THREAD

**Issue by Hank0223** [xindongzhang/MNN_MSSD#24]
請問tflite中mssd.h裡的 OUTPUT_NUM  和 anchor 中的數值 是怎麼計算出來的？

謝謝！

**Comment by xindongzhang** [comment]
> 請問tflite中mssd.h裡的 OUTPUT_NUM 和 anchor 中的數值 是怎麼計算出來的？
> 
> 謝謝！

可以输出anchors这个节点的shapes，就能看到了
