### ISSUE TITLE
请问作者有开源的打算嘛？

### ISSUE THREAD

**Issue by xingfan-git** [xindongzhang/MNN_MSSD#6]
首先谢谢您的代码，本人想用自己的数据库做一些训练，不知道您是否有开源的打算

**Comment by xindongzhang** [comment]
@xingfan-git 你指的是哪一个demo的训练代码呢？

**Comment by xingfan-git** [comment]
抱歉回复晚了，比较感兴趣blazeface的训练代码

**Comment by xindongzhang** [comment]
@xingfan-git 过段时间会考虑开源一个简单的复现版本

**Comment by xingfan-git** [comment]
@xindongzhang 好的，谢谢

**Comment by xindongzhang** [comment]
@xingfan-git 训练的代码资料已经更新到readme上面了

**Comment by xingfan-git** [comment]
@xindongzhang 好的，谢谢！
