### ISSUE TITLE
BlazeFace训练问题

### ISSUE THREAD

**Issue by xingfan-git** [xindongzhang/MNN_MSSD#8]
你好，首先感谢你的代码；我按照你所说的做法，已经基本跑通了模型。但是我在训练的时候，loss一直在10左右震荡，并没有看到收敛的趋势，请问这样子可能是哪里出了问题呢？你最后训练得到的loss是多少呢？

如果方便的话，不知道可不可以上传一下你训练的模型（基于tensorflow的BlazeFace）
谢谢

**Comment by xindongzhang** [comment]
@xingfan-git 这个模型的训练，直接用widerface不太合理，你可以搜集一些好数据进行训练。blazeface主要面对的场景是近距离人脸检测（如手持前置摄像头人脸检测），widerface的训练数据对blazeface模型来说太难了。

**Comment by xingfan-git** [comment]
@xindongzhang 我现在就想先看看这个算法的潜力；你有遇到过训练过程中显示killed，然后训练停止的情况吗？请问你最后得到的loss是多少呢

**Comment by xingfan-git** [comment]
@xindongzhang 请问有推荐的训练集嘛？请问你用的是什么训练集训练的呢？

**Comment by xindongzhang** [comment]
@xingfan-git 可以针对近距离场景洗一批数据训练，或者在widerface上面洗一下也可以

**Comment by xingfan-git** [comment]
@xindongzhang 谢谢，我用celebA做过训练后发现他在celebA数据集上确实表现不错，但结果是针对大人脸的，对于小人脸感受能力很差，请问您有提高他对小人脸敏感度的一些建议嘛？我觉得单纯做fine tune可能不够，需要对模型本身做一些修正？

**Comment by xindongzhang** [comment]
@xingfan-git blazeface模型设计的太紧凑了，原模型上面优化的空间有限的。如果想增加小人脸检测，个人建议可以增加多尺度的anchor prediction（需要增加模型深度），第二个可以尝试增加input resolution。

**Comment by xingfan-git** [comment]
@xindongzhang 好的，谢谢
